module req;

// Header and Body end
const String CLRF = "\r\n\r\n";
const String CLRF_END = "0\r\n\r\n";

// Keys for Headers
const String CONTENT_TYPE = "content-type";
const String DATE = "date";
const String VIA = "via";
const String VARY = "vary";
const String SERVER = "server";
const String CONTENT_LENGTH = "content-length";
const String CONNECTION = "connection";
const String TRANSFER_ENCODING = "transfer-encoding";

// Values in Headers
const String CHUNKED_ENCODING = "chunked";
